### ISSUE TITLE
Exception in PyCharm 2023.3 EAP

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pydevd-odoo#5] opened 2023-11-05 13:28 UTC
PyCharm 2023.3 EAP (Professional Edition)
Build #PY-233.11555.5, built on October 31, 2023
Runtime version: 17.0.9+7-b1087.3 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0

```
Traceback (most recent call last):
  File "/Users/jerzyk/Applications/PyCharm Professional.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 219, in run
    self._on_run()
  File "/Users/jerzyk/Applications/PyCharm Professional.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1932, in _on_run
    xml.write(pydevd_xml.var_to_xml(var_obj, name, evaluate_full_value=True, user_type_renderers=self.user_type_renderers))
  File "/Users/jerzyk/Applications/PyCharm Professional.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_xml.py", line 330, in var_to_xml
    value = _get_default_var_string_representation(v, _type, typeName, format, do_trim)
  File "/Users/jerzyk/Applications/PyCharm Professional.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_xml.py", line 273, in _get_default_var_string_representation
    str_from_provider = _str_from_providers(v, _type, typeName, do_trim)
  File "/Users/jerzyk/Applications/PyCharm Professional.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_xml.py", line 209, in str_from_providers
    return provider.get_str(o, do_trim)
TypeError: OdooRecordSetProvider.get_str() takes 2 positional arguments but 3 were given

```

**Comment by trinhanhngoc** [comment] 2023-11-05 13:55
Hi @jerzyk , 

Thank you for the information. The error is caused by a recent change in PyCharm: https://github.com/JetBrains/intellij-community/commit/edd05b77c02729860958c680e9549b992c275464. I will soon fix this issue.

**Comment by trinhanhngoc** [comment] 2023-11-05 15:19
Hi @jerzyk ,

The new version 1.2.2 has been released with the fix for this issue.

**Closed as completed by trinhanhngoc** 2023-11-05 15:19 UTC
